### ISSUE TITLE
Performance is slowing after completing 100-150 planets.

### ISSUE THREAD

**Issue by zentyk** [Rybar/JS13k2021#1]
Steps:

1. Play the game until completing 100 - 150 planets
2. Music and FPS will begin to down while completing all the planets.
3. Game can be finished but performance is slow.

I noticed that the game slows the performance when the player is near big planets.

**Comment by Rybar** [comment]
Congratulations on being the first person ever to take the time report an issue with one of my poorly developed jam games!

All kidding aside, I'm aware of these performance issues but currently have no plans to address them.  I create game jam games with the intent of them not breaking for 5-10 minutes of play, anything beyond that is gravy.  I am in the planning stages of doing a more finished take on this game idea, but not as a JavaScript game.  Thanks for playing!
